CREATE PROCEDURE [dbo].[PROJ_GET_USER_CLAIMS_BY_USER_ID_SP]
	@USER_ID VARCHAR(254)
AS
 
	SET NOCOUNT ON

	SELECT  Id			AS	USER_CLAIM_ID,
			[UserId]	AS	USER_CLAIM_USER_ID,
			[Type]		AS	USER_CLAIM_TYPE,
			[Value]		AS	USER_CLAIM_VALUE,
			[StatusId]	AS	USER_CLAIM_STATUS_ID
	FROM	dbo.UserClaim (NOLOCK)
	WHERE	[UserId] = @USER_ID
	AND		[StatusId] <> 0


