CREATE PROCEDURE [dbo].[PROJ_GET_ROLE_CLAIMS_BY_USER_ID_SP]
	@USER_ID VARCHAR(254)
AS
 
	SET NOCOUNT ON

	SELECT		TRC.Id				AS	ROLE_CLAIM_ID,
				TRC.[RoleId]		AS	ROLE_CLAIM_ROLE_ID,
				TRC.[Type]			AS	ROLE_CLAIM_TYPE,
				TRC.[Value]			AS	ROLE_CLAIM_VALUE,
				TRC.[StatusId]		AS	ROLE_CLAIM_STATUS_ID
	FROM		dbo.RoleClaim TRC (NOLOCK)
	INNER JOIN	dbo.[Role] TR (NOLOCK)
	ON			TRC.RoleId = TR.Id
	INNER JOIN	dbo.UserRole TUR (NOLOCK)
	ON			TUR.RoleId = TR.Id
	WHERE		TUR.[UserId] = @USER_ID
	AND			TRC.[StatusId] <> 0


